### PR TITLE
Fixes #253 Build-63 error - Admin protocol creation

### LINKED ISSUE #253: Build-63 error - Admin protocol creation
image

Application:
PK-Sim® 7.1.0 - Build 63

Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index

Stack trace:
```
at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at PKSim.Presentation.Presenters.Protocols.ProtocolChartData.createDataToPlot()
   at PKSim.Presentation.Presenters.Protocols.ProtocolChartData..ctor(ICache`2 allSchemaItemDTO, IDimension timeDimension, Unit timeUnit, Double endTimeInMin)
   at PKSim.Presentation.Presenters.Protocols.ProtocolChartPresenter.dataToPlotFrom(ICache`2 protocols, Unit timeUnit)
   at PKSim.Presentation.Presenters.Protocols.ProtocolChartPresenter.PlotProtocols(ICache`2 protocols)
   at PKSim.Presentation.Presenters.Protocols.ProtocolChartPresenter.PlotProtocol(Protocol protocol)
   at PKSim.Presentation.Presenters.Protocols.CreateProtocolPresenter.refreshPlot()
   at PKSim.Presentation.Presenters.Protocols.CreateProtocolPresenter.subPresenterChanged(Object sender, EventArgs eventArgs)
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at OSPSuite.Presentation.Presenters.AbstractPresenter`2.OnStatusChanged(Object sender, EventArgs e)
   at OSPSuite.Presentation.Presenters.AbstractPresenter`2.OnStatusChanged()
   at OSPSuite.Presentation.Presenters.AbstractCommandCollectorPresenter`2.AddCommand(ICommand command)
   at PKSim.Presentation.Presenters.Protocols.AdvancedProtocolPresenter.AddCommand(ICommand commandToAdd)
   at PKSim.Presentation.Presenters.Protocols.ProtocolItemPresenter`2.SetParameterValue(IParameterDTO parameterDTO, Double newValue)
   at PKSim.UI.Views.Protocols.AdvancedProtocolView.<>c__DisplayClass22_0.<setParameterValue>b__0()
   at OSPSuite.UI.Controls.BaseUserControl.<>c__DisplayClass25_0.<OnEvent>b__0()
   at OSPSuite.Utility.Extensions.ExceptionExtensions.DoWithinExceptionHandler(Object callerObject, Action actionToExecute)
```

### PR DESCRIPTION
**Pull request by msevestre**

### CODE REVIEW

**Comment by msevestre** [comment]
@Yuri05 trivial

File: src/PKSim.Presentation/Presenters/Protocols/ProtocolChartData.cs [hunk 1]
```diff
@@ -73,60 +69,45 @@ public ProtocolChartData(ICache<Compound, IReadOnlyList<SchemaItemDTO>> allSchem
          DataTable = new DataTable("Protocol");
          TimeDimension = timeDimension;
          TimeUnit = timeUnit;
-         DataTable.Columns.Add(new DataColumn(GROUPING_NAME, typeof (string)));
-         DataTable.Columns.Add(new DataColumn(TIME, typeof (double)));
-         DataTable.Columns.Add(new DataColumn(DOSE, typeof (double)));
-         DataTable.Columns.Add(new DataColumn(UNIT, typeof (Unit)));
-         DataTable.Columns.Add(new DataColumn(SCHEMA_ITEM, typeof(SchemaItemDTO)));
+         DataTable.AddColumn(GROUPING_NAME);
```
Comment (Yuri05) [inline src/PKSim.Presentation/Presenters/Protocols/ProtocolChartData.cs]: `AddColumn `without type qualifier assumes _Type=string_? Still would prefer `AddColumn<string>` instead

Comment (msevestre) [reply src/PKSim.Presentation/Presenters/Protocols/ProtocolChartData.cs]: It's used like that everywhere and there is no confusion possible when the column name are clearly defined (such as GROUPING_NAME). Nothing to change in my opinion
