### PR TITLE
return null if subject not implementing IWithId

### LINKED ISSUE #2050: Saving a project in PKSim with Parameter Identification => Crash
Application:
PK-Sim® 11.0.0

Unable to cast object of type 'OSPSuite.Presentation.Presenters.ParameterIdentifications.ParameterIdentificationFeedback' to type 'OSPSuite.Core.Domain.IWithId'.

Stack trace:
```
at OSPSuite.Utility.Extensions.ConversionExtensions.DowncastTo[T](Object objectToCast)
   at PKSim.Presentation.Services.WorkspaceLayoutUpdater.createNewWorkspaceLayoutWithOpenPresenters() in C:\dev\PK-Sim\src\PKSim.Presentation\Services\WorkspaceLayoutUpdater.cs:line 70
   at PKSim.Presentation.Services.WorkspaceLayoutUpdater.SaveCurrentLayout() in C:\dev\PK-Sim\src\PKSim.Presentation\Services\WorkspaceLayoutUpdater.cs:line 50
   at PKSim.Presentation.Services.ProjectTask.saveProjectToFile(String fileName) in C:\dev\PK-Sim\src\PKSim.Presentation\Services\ProjectTask.cs:line 181
   at PKSim.Presentation.Services.ProjectTask.SaveCurrentProject() in C:\dev\PK-Sim\src\PKSim.Presentation\Services\ProjectTask.cs:line 130
   at PKSim.Presentation.UICommands.SaveProjectCommand.Execute() in C:\dev\PK-Sim\src\PKSim.Presentation\UICommands\SaveProjectCommand.cs:line 17
   at OSPSuite.Presentation.UICommands.UICommandExtensions.ExecuteWithinExceptionHandler(IUICommand uiCommand, IEventPublisher eventPublisher, IChangePropagator changePropagator)
```

### PR DESCRIPTION
**Pull request by abdelr**
Fixes #2050 (Saving project with parameter identification feedback does not crash)

### CODE REVIEW

File: src/PKSim.Presentation/Services/WorkspaceLayoutUpdater.cs [hunk 1]
```diff
@@ -67,7 +67,7 @@ private WorkspaceLayout createNewWorkspaceLayoutWithOpenPresenters()
          var workspaceLayout = new WorkspaceLayout();
          foreach (var presenter in _applicationController.OpenedPresenters())
          {
-            var withId = presenter.Subject.DowncastTo<IWithId>();
+            var withId = presenter.Subject as IWithId;
             if (withId == null) continue;
```
Comment (msevestre) [inline src/PKSim.Presentation/Services/WorkspaceLayoutUpdater.cs:71]: Please add a test for this

**Review by msevestre — CHANGES_REQUESTED** [review]
Test missing. Required for bug fix. If not possible, please explain why

File: tests/PKSim.Tests/Presentation/WorkspaceLayoutCreatorSpecs.cs [hunk 2]
```diff
@@ -88,4 +90,41 @@ public void should_mark_the_existing_layout_item_as_not_open()
...
+         A.CallTo(() => _existingWorkspaceLayout.LayoutItems).Returns(new List<WorkspaceLayoutItem> { new WorkspaceLayoutItem() });
+      }
+
+      protected override void Because()
+      {
+         sut.SaveCurrentLayout();
+      }
+
+      [Observation]
+      public void should_return_an_object_containing_one_layout_item_for_each_opened_presenter_and_one_for_the_existing_layout_item()
```
Comment (msevestre) [inline tests/PKSim.Tests/Presentation/WorkspaceLayoutCreatorSpecs.cs:125]: Test is ok but this caption is misleading. It does not create a layout item for each opened presenter! You are testing the opposite

**Review by msevestre — CHANGES_REQUESTED** [review]
Please adjust title of test so that it reflect the expecations

**Review by msevestre — APPROVED** [review]
