### PR TITLE
Fixes #2052 renaming uses the wrong type

### LINKED ISSUE #2052: REnaming simulation in v11 asks for new Name for project
I think it's only in v11
image

### PR DESCRIPTION
**Pull request by msevestre**

### CODE REVIEW

File: src/PKSim.Presentation/Services/EntityTask.cs [hunk 1]
```diff
@@ -34,7 +37,7 @@ public ICommand Rename(IEntity elementToRename)
       private ICommand rename(IEntity elementToRename, bool isStructuralChange)
       {
          var dto = _renameObjectDTOFactory.CreateFor(elementToRename);
-         var newName = NewNameFor(elementToRename, dto.UsedNames, dto.ContainerType);
+         var newName = NewNameFor(elementToRename, dto.UsedNames, TypeFor(elementToRename));
```
Comment (msevestre) [inline src/PKSim.Presentation/Services/EntityTask.cs:40]: Just using the wrong tupe after refactoring. ContainerType is always project for bb

**Review by Yuri05 — APPROVED** [review]
