### PR TITLE
#3145-expression-profiles-missing-in-mobi-unless-individual-is-opened…

### LINKED ISSUE #3145: Expression Profiles Missing in MoBi Unless Individual is Opened in PK-Sim (V12)
Description:

When working with the Observer course project in PK-Sim V12, we’ve identified an issue related to expression profiles not being loaded into MoBi unless the individual is explicitly opened in PK-Sim first.

Steps to Reproduce:
1) Open the project in PK-Sim (V12).
2) Without opening the individual, send the simulation to MoBi.
3) In MoBi, observe that no expression profiles are present.
4) Now, go back to PK-Sim, double-click to open the individual.
5) Without modifying anything, send the same simulation to MoBi.
6) This time, the expression profiles appear in MoBi as expected.

The same behavior occurs in PK-Sim V11 (i.e., expression profiles are only visible after opening the individual).

However, in V11, the simulation results in MoBi remain unaffected whether or not the individual was opened beforehand.

In contrast, in V12 the presence or absence of expression profiles significantly affects the simulation outcome.

Video Link:
https://esqlabs.sharepoint.com/:v:/s/MandS/EeF1DDNXsqZNilWRmpEHAdYBOAZrIVhHlQDjra6HNABgcw?e=wvCcpC

### PR DESCRIPTION
**Pull request by benjaperez1983**
Fixes #3145

# Description

We’ve identified an issue related to expression profiles not being loaded into MoBi unless the individual is explicitly opened in PK-Sim first.

## Type of change

Please mark relevant options with an `x` in the brackets.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires documentation changes (link at least one [user](https://github.com/Open-Systems-Pharmacology/docs) or [developer](https://github.com/Open-Systems-Pharmacology/developer-docs) documentation issue):
- [ ] Algorithm update - updates algorithm documentation/questions/answers etc.
- [ ] Other (please describe):

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Integration tests
- [ ] Unit tests
- [ ] Manual tests 
- [ ] No tests required

# Reviewer checklist

Mark everything that needs to be checked before merging the PR.

- [ ] Check if the code is well documented
- [ ] Check if the behavior is what is expected
- [ ] Check if the code is well tested
- [ ] Check if the code is readable and well formatted
- [ ] Additional checks (document below if any)
- [ ] Check if documentation update issue(s) are created if the option `This change requires a documentation update` above is selected

# Screenshots (if appropriate):

# Questions (if appropriate):

### CODE REVIEW

File: src/PKSim.Presentation/Presenters/Main/BuildingBlockExplorerPresenter.cs [hunk 1]
```diff
@@ -181,5 +195,12 @@ private void handleRenamedBuildingBlock(RenamedEvent renamedEvent)
 
          RefreshTreeAfterRename();
       }
+
+      public void Handle(ProjectLoadedEvent eventToHandle)
+      {
+         //This should be here since there are too many ways to open a simulation
+         //and this should be done before any simulation is loaded.
```
Comment (rwmcintosh) [inline src/PKSim.Presentation/Presenters/Main/BuildingBlockExplorerPresenter.cs]: I would change this comment to read something like:
```
// Ensures that all individuals are loaded before any simulations can be lazy loaded.
```

Comment (rwmcintosh) [reply src/PKSim.Presentation/Presenters/Main/BuildingBlockExplorerPresenter.cs]: I guess we should be stating the 'why' as well here. Loading the individual ensures that the expression profiles are created.

I'm not sure if the missing expression profiles are only a problem when converting from a project version that did not support them.

Is this step needed when the project is created with V12?

Comment (Yuri05) [reply src/PKSim.Presentation/Presenters/Main/BuildingBlockExplorerPresenter.cs]: >Is this step needed when the project is created with V12?

I don't think so. Probably only for projects created with PK-Sim versions when expressions profiles were integrated into individuals and not defined as standalone building blocks.

Comment (rwmcintosh) [reply src/PKSim.Presentation/Presenters/Main/BuildingBlockExplorerPresenter.cs]: Then we can probably move this to some post-conversion process.

Comment (msevestre) [reply src/PKSim.Presentation/Presenters/Main/BuildingBlockExplorerPresenter.cs]: I do not understand this at all.. Why should the presneter be repsonsibiel of loading all individuals. This makes me very scared

**Review by msevestre — CHANGES_REQUESTED** [review]
I do not believe that business logic should ever rely on event being thrown and or presenter to react to it. this should be done in the task if at all

File: src/PKSim.Presentation/Presenters/Main/BuildingBlockExplorerPresenter.cs (hunk 1 above)
Comment (rwmcintosh) [reply src/PKSim.Presentation/Presenters/Main/BuildingBlockExplorerPresenter.cs]: Maybe in `ProjectMetaDataToProjectMapper`. We know the project metadata version.

Comment (rwmcintosh) [reply src/PKSim.Presentation/Presenters/Main/BuildingBlockExplorerPresenter.cs]: Ok, not in the mapper, but maybe in `ProjectPersistor` where it's called from. We have the version there too.

File: src/PKSim.Presentation/Services/ProjectTask.cs [hunk 2]
```diff
@@ -325,6 +329,14 @@ private void openProjectFromFile(string projectFile, bool shouldStartWorker = tr
          void openProject()
          {
             _workspace.OpenProject(projectFile);
+
+            if (_workspace.Project.MetaDataVersion < ProjectVersions.V11)
```
Comment (benjaperez1983) [inline src/PKSim.Presentation/Services/ProjectTask.cs]: I`ve added a property to the Project and stored the version there, since we did not find an easy way to get it otherwise.

Please let me know if this is fine.

Thanks!

Comment (rwmcintosh) [reply src/PKSim.Presentation/Services/ProjectTask.cs]: Also, is this the correct version? When were expressions introduced as separate building blocks?

File: src/PKSim.Presentation/Services/ProjectTask.cs [hunk 3]
```diff
@@ -325,6 +329,14 @@ private void openProjectFromFile(string projectFile, bool shouldStartWorker = tr
...
+            {
+               _workspace.Project.All<Individual>().Each(x =>
+               {
+                  _lazyLoadTask.Load(x);
```
Comment (msevestre) [inline src/PKSim.Presentation/Services/ProjectTask.cs]: I don't undertand why we are not doing it when we load the project instead? Can we have a chat about this

**Review by msevestre — COMMENTED** [review]
I don't understand what's going on

File: src/PKSim.Presentation/Services/ProjectTask.cs (hunk 3 above)
Comment (benjaperez1983) [reply src/PKSim.Presentation/Services/ProjectTask.cs]: Of course. let me know when available.
