### PR TITLE
Fixes #1837 export obs data no version

### LINKED ISSUE #1837: Cannot load data repository exported with PKSim V10
PKSim V10.0.198, imported observed data and exported it to PKML. Trying to load it in R results in

```
Error in rClr::clrCall(dataRepositoryTask, "LoadDataRepository", filePath) : 
  Type:    OSPSuite.Utility.Exceptions.OSPSuiteException
Message: PKML file is too old and cannot be converted. Please install the version 8.0 of the OSPSuite to convert the file to a version that can be supported
Method:  Void convert[T](T, Int32, System.Func`2[OSPSuite.Core.Converters.IObjectConverter,System.Func`2[T,System.ValueTuple`2[System.Int32,System.Boolean]]])
Stack trace:
   at OSPSuite.Core.Serialization.Xml.PKMLPersistor.convert[T](T objectToConvert, Int32 objectVersion, Func`2 converterAction)
   at OSPSuite.Core.Serialization.Xml.PKMLPersistor.convertXml(XElement sourceElement, Int32 version)
   at OSPSuite.Core.Serialization.Xml.PKMLPersistor.Load[T](String pkmlFileFullPath, IDimensionFactory dimensionFactory, IObjectBaseFactory objectBaseFactory, IWithIdRepository withIdRepository, ICloneManagerForModel cloneManagerForModel)
   at OSPSuite.R.Services.DataRepositoryTask.LoadDataRepository(String fileName)
```

### PR DESCRIPTION
**Pull request by msevestre**

### CODE REVIEW

File: src/PKSim.Infrastructure/Services/ObservedDataTask.cs [hunk 1]
```diff
@@ -40,15 +40,15 @@ public class ObservedDataTask : OSPSuite.Core.Domain.Services.ObservedDataTask,
          ITemplateTask templateTask,
          IContainerTask containerTask,
          IParameterChangeUpdater parameterChangeUpdater,
-         IObservedDataPersistor observedDataPersistor,
+         IPKMLPersistor pkmlPersistor,
```
Comment (msevestre) [inline src/PKSim.Infrastructure/Services/ObservedDataTask.cs:43]: @Yuri05 Just using the right class without implementing the wheel

**Review by msevestre — COMMENTED** [review]
Trivial change. Merging
