### PR TITLE
Fixes #297 behavior with unknown parameters

### LINKED ISSUE #297: Behavior when importing a snapshot containing unknow parameter
See discussion here
https://github.com/Open-Systems-Pharmacology/PK-Sim/pull/296#discussion_r136382658

The current implementation throws an exception with the name of the unknown parameter.

Another option would be to show the information in some kind of a log file. I favor the exception as loading a snapshot with parameters that are unknown can only lead to issues and wrong expectation. The end user should NEVER trust a snapshot that does not conform to what PK-Sim is expected

### PR DESCRIPTION
**Pull request by msevestre**

### CODE REVIEW

**Comment by msevestre** [comment]
@Yuri05 instead of throwing as soon as something is not found, the load snapshot action is now performed with the log view visible. That way any problem or error is seen right away

File: src/PKSim.BatchTool/ApplicationStartup.cs [hunk 1]
```diff
@@ -34,16 +32,6 @@ public static void Start()
...
-
-         initializeLogger();
-      }
-
-      private static void initializeLogger()
-      {
-         var loggerFactory = IoC.Resolve<ILoggerFactory>();
-
-         loggerFactory
-            .AddPresenter();
```
Comment (msevestre) [inline src/PKSim.BatchTool/ApplicationStartup.cs]: The log presenter is now added by default when using the PKSim.UI

File: src/PKSim.Core/Snapshots/Mappers/CompoundMapper.cs [hunk 2]
```diff
@@ -158,7 +158,7 @@ private IEnumerable<IParameter> changedGroupParameters(IContainer container, str
       {
          var alternativeGroup = compound.ParameterAlternativeGroup(alternativeGroupName);
          var alteratives = await _alternativeMapper.MapToSnapshots(alternativeGroup.AllAlternatives);
-         var definedAlternatives = alteratives?.Where(x => x != null).ToArray();
+         var definedAlternatives = alteratives?.ToArray();
```
Comment (msevestre) [inline src/PKSim.Core/Snapshots/Mappers/CompoundMapper.cs]: This is not required anymore. I have changed the MapToSnapshots to NOT return any null object

Comment (msevestre) [inline src/PKSim.Core/Snapshots/Mappers/CompoundMapper.cs]: This is not required anymore. I have changed the MapToSnapshots to NOT return any null object

File: src/PKSim.Core/Snapshots/Mappers/CurveMapper.cs [hunk 3]
```diff
@@ -39,12 +43,24 @@ public CurveMapper(CurveOptionsMapper curveOptionsMapper, IDimensionFactory dime
          curve.CurveOptions.UpdateFrom(curveOptions);
 
          var yData = findCurveWithPath(snapshot.Y, simulationAnalysisContext.DataRepositories);
+         if (yData == null)
+         {
+            _logger.AddToLog(PKSimConstants.Error.CouldNotFindQuantityWithPath(snapshot.Y));
```
Comment (msevestre) [inline src/PKSim.Core/Snapshots/Mappers/CurveMapper.cs]: That's the only thing that needs to be done when something should be logged. Grab the logger and write

File: src/PKSim.Core/Snapshots/Mappers/ParameterMapper.cs [hunk 4]
```diff
@@ -57,6 +75,12 @@ public override Task<SnapshotParameter> MapToSnapshot(IParameter modelParameter)
          if (snapshot.Value == null)
             return parameter;
 
+         var displayUnit = ModelValueFor(snapshot.Unit);
+         if (!parameter.Dimension.HasUnit(displayUnit))
```
Comment (msevestre) [inline src/PKSim.Core/Snapshots/Mappers/ParameterMapper.cs]: This can happen either if snapshot is edited by hand OR using some old projects where unit was sometime missing

File: src/PKSim.Presentation/Services/ProjectTask.cs [hunk 5]
```diff
@@ -224,34 +222,16 @@ public void LoadProjectFromSnapshot()
...
-         var fileName = _dialogCreator.AskForFileToOpen(message, Constants.Filter.JSON_FILE_FILTER, Constants.DirectoryKey.REPORT);
-         if (string.IsNullOrEmpty(fileName))
-            return;
-
          closeProject();
 
-         _heavyWorkManager.Start(LoadSnapshotIntoWorkspace, PKSimConstants.UI.LoadingSnapshot);
-
-         void LoadSnapshotIntoWorkspace()
+         using (var presenter = _applicationController.Start<ILoadProjectFromSnapshotPresenter>())
```
Comment (msevestre) [inline src/PKSim.Presentation/Services/ProjectTask.cs]: Starts the UI instead of doing everything in HeavyWorkManager

File: src/PKSim.UI/BootStrapping/ApplicationStartup.cs [hunk 6]
```diff
@@ -69,6 +71,16 @@ public void InitializeForStartup()
...
+
+         configureLogger(container);
+      }
+
+      private void configureLogger(IContainer container)
+      {
+         var loggerFactory = container.Resolve<ILoggerFactory>();
+         loggerFactory
+            .AddPresenter()
+            .AddDebug();
```
Comment (msevestre) [inline src/PKSim.UI/BootStrapping/ApplicationStartup.cs]: Also add the debug logger. That way we always see what's happening in the debug windown

**Comment by msevestre** [comment]
Need to merge that to get going with next feature. Feel free to review when you have time
