### PR TITLE
V3-1799 UpdateParameterIdentification Using

### LINKED ISSUE #3086: Importer: "Reload under the same settings" does not work
Application:
PK-Sim® 11.2.142

Key 'Compartment' could not be found

Stack trace:

at OSPSuite.Utility.Collections.Cache`2.<>c.<.ctor>b__11_0(TKey key)
   at OSPSuite.Utility.Collections.Cache`2.get_Item(TKey key)
   at OSPSuite.Presentation.Services.DataImporter.<>c__DisplayClass6_0.<AreFromSameMetaDataCombination>b__0(KeyValuePair`2 keyValuePair)
   at System.Linq.Enumerable.All[TSource](IEnumerable`1 source, Func`2 predicate)
   at OSPSuite.Presentation.Services.DataImporter.AreFromSameMetaDataCombination(DataRepository sourceDataRepository, DataRepository targetDataRepository)
   at OSPSuite.Presentation.Services.DataImporter.<>c__DisplayClass7_0.<repositoryExistsInList>b__0(DataRepository dataRepo)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at OSPSuite.Presentation.Services.DataImporter.repositoryExistsInList(IEnumerable`1 dataRepositoryList, DataRepository targetDataRepository)
   at OSPSuite.Presentation.Services.DataImporter.<>c__DisplayClass5_0.<CalculateReloadDataSetsFromConfiguration>b__0(DataRepository dataSet)
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at OSPSuite.Presentation.Services.DataImporter.CalculateReloadDataSetsFromConfiguration(IReadOnlyList`1 dataSetsToImport, IReadOnlyList`1 existingDataSets)
   at PKSim.Infrastructure.Services.ImportObservedDataTask.AddAndReplaceObservedDataFromConfigurationToProject(ImporterConfiguration configuration, IEnumerable`1 observedDataFromSameFile)
   at PKSim.Presentation.UICommands.ReloadAllObservedDataCommand.PerformExecute()
   at OSPSuite.Presentation.UICommands.ObjectUICommand`1.Execute()
   at OSPSuite.Presentation.UICommands.UICommandExtensions.ExecuteWithinExceptionHandler(IUICommand uiCommand, IEventPublishe

### PR DESCRIPTION
**Pull request by benjaperez1983**
Fixes #3086 

# Description

Whe using the funtion to "Reload under the same settings", and the updated data set has less values that the previous one and it was used in a PI

## Type of change

Please mark relevant options with an `x` in the brackets.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires documentation changes (link at least one [user](https://github.com/Open-Systems-Pharmacology/docs) or [developer](https://github.com/Open-Systems-Pharmacology/developer-docs) documentation issue):
- [ ] Algorithm update - updates algorithm documentation/questions/answers etc.
- [ ] Other (please describe):

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Integration tests
- [x] Unit tests -> on Core
- [x] Manual tests 
- [ ] No tests required

# Reviewer checklist

Mark everything that needs to be checked before merging the PR.

- [ ] Check if the code is well documented
- [ ] Check if the behavior is what is expected
- [ ] Check if the code is well tested
- [ ] Check if the code is readable and well formatted
- [ ] Additional checks (document below if any)
- [ ] Check if documentation update issue(s) are created if the option `This change requires a documentation update` above is selected

# Screenshots (if appropriate):

# Questions (if appropriate):

### CODE REVIEW

File: src/PKSim.Infrastructure/Services/ImportObservedDataTask.cs [hunk 1]
```diff
@@ -87,8 +87,9 @@ public ImporterConfiguration OpenXmlConfiguration()
 
       public void AddAndReplaceObservedDataFromConfigurationToProject(ImporterConfiguration configuration, IEnumerable<DataRepository> observedDataFromSameFile)
       {
+         var lstObservedDataFromSameFile = observedDataFromSameFile.ToList();
```
Comment (rwmcintosh) [inline src/PKSim.Infrastructure/Services/ImportObservedDataTask.cs]: Can you change the argument so it's `IReadOnlyList<DataRepository> observedDataFromSameFile` Then you won't have to create the list version with the funky name.

The method probably pre-dates the introduction of `IReadOnlyList` in .NET

**Review by rwmcintosh — CHANGES_REQUESTED** [review]
Try this parameter type change and link the PR to an issue in PK-Sim.
I also know this is related to a change in OSPSuite.Core, so link that in the comments as well to give context to the next reviewer.

**Comment by benjaperez1983** [comment]
This Issue is related to> https://github.com/Open-Systems-Pharmacology/OSPSuite.Core/issues/2179

**Review by rwmcintosh — APPROVED** [review]

**Comment by rwmcintosh** [comment]
Is there an issue # in PK-Sim for this?

File: templates
Comment (Yuri05) [inline templates:1]: please update to the latest version of the templates module, otherwsie it would be downgraded

**Review by Yuri05 — CHANGES_REQUESTED** [review]
s. https://github.com/Open-Systems-Pharmacology/PK-Sim/pull/3084/files?w=1#r1973678976

**Review by Yuri05 — CHANGES_REQUESTED** [review]
templates submodule still downgraded

File: templates
Comment (benjaperez1983) [reply templates:1]: @Yuri05 Would you help me out here?
I just ran git checkout develop over the 3 files but I get no changes at all. 
In fact not sure how this changes made it here. What are this templates exaclty and how to update them?

**Review by Yuri05 — APPROVED** [review]
