### PR TITLE
Fixes #486 Hidden parameter with a value changed by the user (IsFixed…

### LINKED ISSUE #486: Hidden parameter with a value changed by the user (IsFixedValue = true) should be shown
This can happen when a hidden parameter is edited in MoBi and the simulation is imported back into PKSim. 
There is no way at the moment to see this change in PK-Sim which can lead to serious frustration when trying to understand why something is not working as expected

### PR DESCRIPTION
**Pull request by msevestre**
…Value = true) should be shown

### CODE REVIEW

File: src/PKSim.Presentation/Presenters/Parameters/ParameterSetPresenter.cs [hunk 1]
```diff
@@ -149,10 +150,17 @@ public bool IsFormulaNotFixed(IParameterDTO parameterDTO)
 
       public virtual void Edit(IEnumerable<IParameter> parameters)
       {
-         _visibleParameters = parameters.Where(x => x.Visible).ToList();
+         _visibleParameters = parameters.Where(shouldShowParameter).ToList();
          _pathCache = _parameterTask.PathCacheFor(_visibleParameters);
       }
 
+      private bool shouldShowParameter(IParameter parameter)
```
Comment (msevestre) [inline src/PKSim.Presentation/Presenters/Parameters/ParameterSetPresenter.cs]: I have just created a function and extended the logic

File: tests/PKSim.Tests/Presentation/MultiParameterEditPresenterSpecs.cs [hunk 2]
```diff
@@ -250,6 +248,59 @@ public void should_hide_the_distribution_if_unvisible()
...
+      private IParameter _hiddenIsFixedParameter;
+      private IParameter _hiddenIsNotDefaultParameter;
+      private List<ParameterDTO> _allParameterDTO;
+      private List<IParameter> _displayedParameters;
+
+      protected override void Context()
+      {
+         base.Context();
+         _visibleParameter = new PKSimParameter {Visible = true};
+         _hiddenUnchangedParameter = new PKSimParameter {Visible = false, IsDefault = true};
```
Comment (msevestre) [inline tests/PKSim.Tests/Presentation/MultiParameterEditPresenterSpecs.cs]: Our different types of parameters here
Visible
Hidden unchanged
Hidden IsFixedValue = true (Formula was changed to constant....this should result in IsDefault false I believe)
Hidden IsDefault = false

**Comment by msevestre** [comment]
@Yuri05 Going to merge that... Please review
