### PR TITLE
Fixes #656 PK-Sim 7.3 beta: Error Id lXL0oCyxmEissfeX6aL8oQ not unique

### LINKED ISSUE #656: PK-Sim 7.3 beta: Error "Id lXL0oCyxmEissfeX6aL8oQ not unique"
To reproduce:
1. In simulation “Sol_Tab_1” of attached file : Compounds/Test -> Solubility table -> “Edit Table” -> change solubility at pH 5 -> Run simulation

2. "Commit to Building Block" (change of solubility of molecule)

3. At Molecule Building Block for molecule “Test”: Solubility “Table” -> Edit Table -> change solubility at pH 5

4. Simulation: Update from building block -> Run simulation

5. Save file and re-open file

6. Open simulation “Sol_Tab_1”

-> An exception "Id lXL0oCyxmEissfeX6aL8oQ not unique" is thrown and the solubility table and other parameters are gone.
[ph_Sol.zip](https://github.com/Open-Systems-Pharmacology/PK-Sim/files/1968188/ph_Sol.zip)

Application:
PK-Sim® 7.3.0.9 - EAP

Id lXL0oCyxmEissfeX6aL8oQ not unique

Stack trace:
```
at OSPSuite.Core.Domain.WithIdRepository.Register(IWithId objectWithId)
   at OSPSuite.Core.Serialization.Xml.SerializationContext.Register(IWithId withId)
   at OSPSuite.Core.Serialization.Xml.ObjectBaseXmlSerializer`1.TypedDeserialize(T objectToDeserialize, XElement outputToDeserialize, SerializationContext serializationContext)
   at OSPSuite.Core.Serialization.Xml.TableFormulaXmlSerializerBase`1.TypedDeserialize(TFormula tableFormula, XElement formulaElement, SerializationContext serializationContext)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.Deserialize(XElement outputToDeserialize, TContext context)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.Deserialize[T](XElement outputToDeserialize, TContext context)
   at OSPSuite.Serializer.Xml.XmlEnumerationNodeMapper`3.valueFromChildNode(XElement childElement, TContext context)
   at OSPSuite.Serializer.Xml.XmlEnumerationNodeMapper`3.Deserialize(TObject objectToDeserialize, XElement element, TContext context)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.TypedDeserialize(TObject objectToDeserialize, XElement outputToDeserialize, TContext context)
   at OSPSuite.Core.Serialization.Xml.FormulaCacheXmlSerializer.TypedDeserialize(FormulaCache formulaCache, XElement formulaCacheNode, SerializationContext serializationContext)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.Deserialize(XElement outputToDeserialize, TContext context)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.Deserialize[T](XElement outputToDeserialize, TContext context)
   at OSPSuite.Core.Serialization.Xml.Extensions.XmlSerializerRepositoryExtensions.DeserializeFormulaCacheIn(IXmlSerializerRepository`1 serializerRepository, XElement element, SerializationContext serializationContext)
   at PKSim.Infrastructure.Serialization.Xml.Serializers.BuildingBlockXmlSerializer`1.TypedDeserialize(T buildingBlock, XElement element, SerializationContext serializationContext)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.Deserialize(XElement outputToDeserialize, TContext context)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.Deserialize[T](XElement outputToDeserialize, TContext context)
   at PKSim.Infrastructure.Serialization.Xml.Serializers.UsedBuildingBlockXmlSerializer.TypedDeserialize(UsedBuildingBlock usedBuildingBlock, XElement usedBuildingBlockNode, SerializationContext context)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.Deserialize(XElement outputToDeserialize, TContext context)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.Deserialize[T](XElement outputToDeserialize, TContext context)
   at OSPSuite.Serializer.Xml.XmlEnumerationNodeMapper`3.valueFromChildNode(XElement childElement, TContext context)
   at OSPSuite.Serializer.Xml.XmlEnumerationNodeMapper`3.Deserialize(TObject objectToDeserialize, XElement element, TContext context)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.TypedDeserialize(TObject objectToDeserialize, XElement outputToDeserialize, TContext context)
   at OSPSuite.Core.Serialization.Xml.ObjectBaseXmlSerializer`1.TypedDeserialize(T objectToDeserialize, XElement outputToDeserialize, SerializationContext serializationContext)
   at PKSim.Infrastructure.Serialization.Xml.Serializers.BuildingBlockXmlSerializer`1.TypedDeserialize(T buildingBlock, XElement element, SerializationContext serializationContext)
   at PKSim.Infrastructure.Serialization.Xml.Serializers.SimulationXmlSerializer`1.TypedDeserialize(TSimulation simulation, XElement simulationElement, SerializationContext context)
   at OSPSuite.Serializer.Xml.XmlSerializer`2.Deserialize(Object objectToDeserialize, XElement outputToDeserialize, TContext context)
   at PKSim.Infrastructure.Serialization.Xml.XmlReader`1.ReadFrom(T objectToRead, XElement element, SerializationContext serializationContext)
   at PKSim.Infrastructure.Serialization.Xml.XmlSerializationManager.Deserialize[TObject](TObject objectToDeserialize, Byte[] serializationBytes, SerializationContext serializationContext)
   at PKSim.Core.Services.CompressedSerializationManager.Deserialize[TObject](TObject objectToDeserialize, Byte[] serializationBytes, SerializationContext serializationContext)
   at PKSim.Infrastructure.Services.ContentLoader.LoadContentFor[T](T objectToLoad)
   at PKSim.Infrastructure.Services.LazyLoadTask.loadObjectBase[T](T objectToLoad)
   at PKSim.Infrastructure.Services.LazyLoadTask.Load[TObject](TObject objectToLoad)
   at PKSim.Presentation.Core.SingleStartPresenterTask.<>c__DisplayClass5_0`1.<StartForSubject>b__0()
   at OSPSuite.Presentation.Services.HeavyWorkManager.doWork()
   at OSPSuite.Presentation.Services.HeavyWorkManager.<.ctor>b__9_1(Object o, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
```

### PR DESCRIPTION
**Pull request by msevestre**

### CODE REVIEW

File: src/PKSim.Presentation/Services/CompoundAlternativeTask.cs [hunk 1]
```diff
@@ -241,7 +241,7 @@ public ICommand EditSolubilityTableFor(IParameter parameter)
             if (!tablePresenter.Edit(parameter))
                return new PKSimEmptyCommand();
 
-            return _parameterTask.SetParameterFomula(parameter, tablePresenter.EditedFormula);
+            return _parameterTask.UpdateTableFormula(parameter, tablePresenter.EditedFormula);
```
Comment (msevestre) [inline src/PKSim.Presentation/Services/CompoundAlternativeTask.cs]: This is not required here but much consistent with the way it should be used anyways. Instead of SETTING the formula, I am updating the formula with the edited one

File: src/PKSim.Presentation/Services/EditParameterPresenterTask.cs [hunk 2]
```diff
@@ -53,7 +53,7 @@ public void EditTableFor(ICommandCollector presenter, IParameterDTO parameterDTO
             if (!tablePresenter.Edit(parameter))
                return;
 
-            presenter.AddCommand(_parameterTask.SetParameterFomula(parameter, tablePresenter.EditedFormula));
+            presenter.AddCommand(_parameterTask.UpdateTableFormula(parameter, tablePresenter.EditedFormula));
```
Comment (msevestre) [inline src/PKSim.Presentation/Services/EditParameterPresenterTask.cs]: Same here. This was really the issue. When the formula was edited, BOTH parameter in simulation and building block parmaeter in simulation would get the same reference to the formula, leading to two formulas with different ids after deserializing

**Comment by msevestre** [comment]
Going to merge as this might help with #654
