### PR TITLE
Fixes #1384 population time profile fixes

### LINKED ISSUE #1384: Remove organism from path in time profile (Population)

### PR DESCRIPTION
**Pull request by msevestre**

### CODE REVIEW

File: src/PKSim.Presentation/Presenters/PopulationAnalyses/PopulationAnalysisAvailablePKParametersPresenter.cs [hunk 1]
```diff
@@ -84,8 +91,9 @@ public void QuantityPKParameterSelected(QuantityPKParameterDTO quantityPKParamet
       private IReadOnlyCollection<QuantityPKParameterDTO> availablePKParametersFor(IQuantity quantity)
       {
          var quantityDTO = _quantitySelectionDTOMapper.MapFrom(quantity);
+         var quantityDisplayPth = _quantityDisplayPathMapper.DisplayPathAsStringFor(quantity, addSimulationName: false);
```
Comment (msevestre) [inline src/PKSim.Presentation/Presenters/PopulationAnalyses/PopulationAnalysisAvailablePKParametersPresenter.cs]: This will be a unified path were organism will be removed and simulation will not be visible

Comment (msevestre) [reply src/PKSim.Presentation/Presenters/PopulationAnalyses/PopulationAnalysisAvailablePKParametersPresenter.cs]: problem also for PK Parameters

File: src/PKSim.Presentation/Presenters/PopulationAnalyses/PopulationAnalysisOutputSelectionPresenter.cs [hunk 2]
```diff
@@ -90,23 +99,16 @@ public void AddOutput()
 
       private void addOutput(QuantitySelectionDTO output)
       {
-         addOutput(new[] {output});
+         //Do not add simulation name as the output are already constructed as the intersection of all outputs available for all simulations
+         var displayPathAsString = _quantityDisplayPathMapper.DisplayPathAsStringFor(output.Quantity, addSimulationName: false);
```
Comment (msevestre) [inline src/PKSim.Presentation/Presenters/PopulationAnalyses/PopulationAnalysisOutputSelectionPresenter.cs]: This will be a unified path were organism will be removed and simulation will not be visible

Comment (Yuri05) [reply src/PKSim.Presentation/Presenters/PopulationAnalyses/PopulationAnalysisOutputSelectionPresenter.cs]: For individual simulations: can it be done the way that:
* in individual simulation **comparison** chart simulation name is added, but
* in individual simulation chart simulation name is not added

?

File: src/PKSim.Presentation/Presenters/PopulationAnalyses/CreatePopulationAnalysisPresenter.cs [hunk 3]
```diff
@@ -114,6 +124,19 @@ protected virtual bool Edit(IPopulationDataCollector populationDataCollector, Po
          return true;
       }
 
+      protected virtual void AddDefaultAnalysisField()
+      {
+        //Add grouping by simulation name when comparing simulations as it is a step that is always required in order to display something meaningful
+        if (!_populationDataCollector.IsAnImplementationOf<PopulationSimulationComparison>())
+           return;
+
+        var simulationNameField = _populationAnalysisFieldFactory.CreateFor(CoreConstants.Covariates.SIMULATION_NAME, _populationDataCollector);
```
Comment (msevestre) [inline src/PKSim.Presentation/Presenters/PopulationAnalyses/CreatePopulationAnalysisPresenter.cs]: @Yuri05 Add simulation name as color grouping field if not already defined.
