### PR TITLE
Fixes #3246

### LINKED ISSUE #3163: 12.1 Confusing LockUI/ProgressBar behaviour when running simulations
In 12.1, when I start running an individual or population simulation, the rest of the UI is not locked anymore.
Now, if I open another simulation which **was not loaded before**, the calculation progress bar disappears.
The only possibility to reanimate it seems to start another simulation run in parallel.

This is new in 12.1 (in 12.0, the rest of the UI was locked - except the STOP button - till the calculation was completed).

### LINKED ISSUE #3246: 12.1 Simulation run fails => Run Buttons remain inactive
[simple_ErrorRun.zip](https://github.com/user-attachments/files/22237685/simple_ErrorRun.zip)
If a simulation run exists with error - Run buttons remain inactive (until the active simulation is changed)

Image

### PR DESCRIPTION
**Pull request by msevestre**
Fixes #3246
Fixes #3163

# Description
Running a simulation=> we cannot run in again unless we activate it again by switchign tabs for instance.
Now we have a way to superseed the STATE by using the parameter given

Also fixes #3163 by simply removing the progress bar when lazy loading an object. This does not make sense any more as ONLY one progress bar can be active at a time

## Type of change

Please mark relevant options with an `x` in the brackets.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires documentation changes (link at least one [user](https://github.com/Open-Systems-Pharmacology/docs) or [developer](https://github.com/Open-Systems-Pharmacology/developer-docs) documentation issue):
- [ ] Algorithm update - updates algorithm documentation/questions/answers etc.
- [ ] Other (please describe):

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Integration tests
- [ ] Unit tests
- [x] Manual tests 
- [ ] No tests required

# Reviewer checklist

Mark everything that needs to be checked before merging the PR.

- [ ] Check if the code is well documented
- [ ] Check if the behavior is what is expected
- [ ] Check if the code is well tested
- [ ] Check if the code is readable and well formatted
- [ ] Additional checks (document below if any)
- [ ] Check if documentation update issue(s) are created if the option `This change requires a documentation update` above is selected

# Screenshots (if appropriate):

# Questions (if appropriate):

### CODE REVIEW

File: src/PKSim.Presentation/Presenters/Main/MenuAndToolBarPresenter.cs [hunk 1]
```diff
@@ -276,18 +276,21 @@ private void disableSimulationItems()
          updateSimulationItemsAccordingToSimulationState();
       }
 
-      private void updateSimulationItemsAccordingToSimulationState(bool isRunning = false)
```
Comment (msevestre) [inline src/PKSim.Presentation/Presenters/Main/MenuAndToolBarPresenter.cs:279]: this default value was not correct. because it looks like by default it's never running and since we were combining it with the state coming from the ISRunning extension method, it would alwyas default to this value which was wrong since it's updated AFTER the event are raised

File: src/PKSim.Presentation/Presenters/Main/MenuAndToolBarPresenter.cs [hunk 2]
```diff
@@ -276,18 +276,21 @@ private void disableSimulationItems()
...
+      /// </summary>
+      /// <param name="isSimulationRunning">If defined, super seeds the simulationState </param>
+      private void updateSimulationItemsAccordingToSimulationState(bool? isSimulationRunning = null)
+      {
+         var enabled = _simulationState.IsActivated && _enabled;
+         var resultsEnabled = enabled && _simulationState.HasResult;
+         var enablePopSimulationItems = enabled && !_simulationState.IsIndividual;
+         var enableIndividualSimulationItems = enabled && _simulationState.IsIndividual;
+         var enabledPKSimSimulationOnlyItems = enabled && !_simulationState.IsImported;
+         var isRunning = enabled && (isSimulationRunning ?? _simulationState.IsRunning);
```
Comment (msevestre) [inline src/PKSim.Presentation/Presenters/Main/MenuAndToolBarPresenter.cs:290]: either we pass a flag and we use it if defined, OTHERWUSE we use the state. We do not combine these two flags because this will almost always be wrong

File: src/PKSim.Presentation/Presenters/Main/MenuAndToolBarPresenter.cs [hunk 3]
```diff
@@ -336,11 +337,11 @@ public void Handle(SimulationResultsUpdatedEvent eventToHandle)
          updateSimulationItemsFor(eventToHandle.Simulation as Simulation);
       }
 
-      private void updateSimulationItemsFor(Simulation simulation, bool isRunning = false)
+      private void updateSimulationItemsFor(Simulation simulation, bool? isRunning = null)
       {
          var activeSimulation = _activeSubjectRetriever.Active<Simulation>();
-         bool simIsActive = (activeSimulation != null) && (activeSimulation == simulation);
-         updateSimulationStateFrom(simulation, isActiveSimulation: simIsActive);
+         var isActiveSimulation = Equals(activeSimulation, simulation);
```
Comment (msevestre) [inline src/PKSim.Presentation/Presenters/Main/MenuAndToolBarPresenter.cs:343]: resharper suggestions is accurate. We should not dismiss them

**Review by msevestre — COMMENTED** [review]
This fixes the bug but I feel that we have a bigger issue. The simulationState was meant to be used when we had ONE simulation running. Now we can have multiple so quick switching between tabs and running stopping simulation could potentiall;y lead to weird behavior. Maybe mostly theoretical but we should look at this eventually

**Review by Yuri05 — APPROVED** [review]

**Comment by Yuri05** [comment]
Approved... but meanwhile I'm lost in the logic. Just hope it works...

**Comment by msevestre** [comment]
Yeah the implementation does not make sense for multiple runs. I don’t this it really can lead to non sense anyways. It’s all a matter of timing and the way we check that a simulation is running is off
