### PR TITLE
Fixes #1437 missing files

### LINKED ISSUE #1437: Cannot initialize PKSim.R.Api
When calling 

`createIndividualCharacteristics(species = Species$Rat, gender = Gender$Unknown, weight = 0.23)`

from R, an error is thrown:

```
Error in rClr::clrCallStatic("PKSim.R.Api", "InitializeOnce") : 
  Type:    System.IO.FileNotFoundException
Message: Die Datei "D:\Documents\R\win-library\3.6\rClr\libs\OSPSuite.Dimensions.xml" konnte nicht gefunden werden.
Method:  Void WinIOError(Int32, System.String)
```

Somohow the path to `OSPSuite.Dimensions.xml` is wrong (looking for the file in the rClr folder and not the ospsuite).

### PR DESCRIPTION
**Pull request by msevestre**

### CODE REVIEW

File: src/PKSim.R/Bootstrap/ApplicationStartup.cs [hunk 1]
```diff
@@ -49,7 +51,10 @@ private IContainer performInitialization()
          }
 
          var configuration = container.Resolve<IPKSimConfiguration>();
-         configuration.PKSimDbPath = Path.Combine(new FileInfo(Assembly.GetAssembly(GetType()).Location).DirectoryName, CoreConstants.PK_SIM_DB_FILE);
+         var currentPath = new FileInfo(Assembly.GetAssembly(GetType()).Location).DirectoryName;
+         configuration.PKSimDbPath = Path.Combine(currentPath, CoreConstants.PK_SIM_DB_FILE);
+         configuration.PKParametersFilePath = Path.Combine(currentPath, Constants.Files.PK_PARAMETERS_FILE_NAME);
```
Comment (msevestre) [inline src/PKSim.R/Bootstrap/ApplicationStartup.cs]: @Yuri05 Setting the path explicitely.
