### PR TITLE
Fixes #529 Adding new metabolization process - metabolite selection i…

### LINKED ISSUE #529: Adding new metabolization process - metabolite selection ignored
1) Open the "Paracetamol"-example, or any other PK-Sim project with metabolizing enzyme expression and at least two compounds (in the latter case, open the respective compounds in the next steps)
2) Open the "Paracetamol"-compound and navigate to the tab "ADME"
3) Select "Add metabolizing Enzyme". Select any expressed enzyme, and some other compound under "Metabolite". As "process type", select "In vitro clearance - First Order" (important step to reproduce).

image

4) After pressing "OK", no metabolite is selected.
image

### PR DESCRIPTION
**Pull request by msevestre**
…gnored

### CODE REVIEW

File: src/PKSim.Presentation/Presenters/Compounds/CreateEnzymaticProcessPresenter.cs [hunk 1]
```diff
@@ -42,16 +44,33 @@ private IEnumerable<Compound> allPossibleMetabolites()
          return _buildingBlockRepository.All<Compound>()
             .OrderBy(x => x.Name);
       }
+      
+      protected override void Rebind(EnzymaticProcess enzymaticProcess, Compound compound)
```
Comment (msevestre) [inline src/PKSim.Presentation/Presenters/Compounds/CreateEnzymaticProcessPresenter.cs]: This is the actual code here. It is required to save the metabolite name before updating the view with thew new selected template

Comment (msevestre) [reply src/PKSim.Presentation/Presenters/Compounds/CreateEnzymaticProcessPresenter.cs]: This is really the only change in this code. All the rest is code reformatting using terser syntax and tests

File: tests/PKSim.Tests/Presentation/CreatePartialProcessPresenterSpecs.cs [hunk 2]
```diff
@@ -83,5 +92,11 @@ public void should_not_reset_the_name_and_protein_entered_by_the_user()
          _process2DTO.MoleculeName.ShouldBeEqualTo("Protein");
          _process2DTO.DataSource.ShouldBeEqualTo("Lab");
       }
+      
+      [Observation]
+      public void should_not_reset_the_name_of_the_metabolite()
+      {
+         _enzymaticPartialProcessDTO.Metabolite.ShouldBeEqualTo(_template1.MetaboliteName);
```
Comment (msevestre) [inline tests/PKSim.Tests/Presentation/CreatePartialProcessPresenterSpecs.cs]: That's the test here. Before the Metabolite was empty. With the implementation, the Metabolite is whatever was set before the update
