### PR TITLE
Fixes #691 CLI run and export: Crash when input folder does not exist…

### LINKED ISSUE #691: CLI run and export: Crash when input folder does not exist => handling as with snapshot
Like in issue #686 an exception error will crash the program when invoked with "run" or "export" if the input folder does not exist. PKsim.CLI should behave in the same way as implemented for "snap".

### PR DESCRIPTION
**Pull request by msevestre**
… => handling as with snapshot

### CODE REVIEW

File: src/PKSim.BatchTool/Presenters/IBatchPresenter.cs [hunk 1]
```diff
@@ -55,7 +55,7 @@ protected BatchPresenter(TView view, TBatchRunner batchRunner, IDialogCreator di
          }
          catch (Exception e)
          {
-            _batchLogger.AddError(e.ExceptionMessageWithStackTrace());
+            _batchLogger.AddException(e);
```
Comment (msevestre) [inline src/PKSim.BatchTool/Presenters/IBatchPresenter.cs]: The behavior is encapsulated in this class

File: src/PKSim.CLI.Core/RunOptions/ExportRunOptions.cs [hunk 2]
```diff
@@ -1,14 +1,35 @@
...
+
+      public IBusinessRuleSet Rules { get; } = new BusinessRuleSet();
+
+      public string OutputFolder
+      {
+         get => _outputFolder;
+         set => SetProperty(ref _outputFolder, value);
+      }
+
+      public ExportRunOptions()
```
Comment (msevestre) [inline src/PKSim.CLI.Core/RunOptions/ExportRunOptions.cs]: adding rules for this guy as well

File: src/PKSim.CLI/Program.cs [hunk 3]
```diff
@@ -38,13 +39,21 @@ static int Main(string[] args)
...
          var logger = initializeLogger(command);
          logger.AddInfo($"Starting {command.Name.ToLower()} run with arguments:\n{command}");
          ApplicationStartup.Start();
          var runner = IoC.Resolve<IBatchRunner<TRunOptions>>();
-         runner.RunBatchAsync(command.ToRunOptions()).Wait();
+         try
+         {
+            runner.RunBatchAsync(command.ToRunOptions()).Wait();
+         }
+         catch (Exception e)
```
Comment (msevestre) [inline src/PKSim.CLI/Program.cs]: Exceptions need to be caught and display using the logger

**Comment by msevestre** [comment]
@Yuri05 Please review. Going to merge to move forward
