### PR TITLE
Fixes #2981 Error when trying to edit a table parameter in simulation

### LINKED ISSUE #2981: V12: Error when trying to edit a table parameter in simulation
Taken the latest source from GitHub; Clean+Rebuild solution.

[12.0_Human_Oral_BiDaily_TableFormulation.pksim5.zip](https://github.com/user-attachments/files/17117197/12.0_Human_Oral_BiDaily_TableFormulation.pksim5.zip)
grafik

```
Application:
PK-Sim® 12.0.0

Missing dependency.
Component PKSim.Presentation.Presenters.Parameters.IEditTableParameterPresenter-PKSim.Presentation.Presenters.Parameters.EditTableParameterPresenter has a dependency on PKSim.Presentation.Presenters.Parameters.ITableParameterPresenter, which could not be resolved.
Make sure the dependency is correctly registered in the container as a service, or provided as inline argument.

Stack trace:

at Castle.MicroKernel.Resolvers.DefaultDependencyResolver.ResolveFromKernelByType(CreationContext context, ComponentModel model, DependencyModel dependency)
   at Castle.MicroKernel.Resolvers.DefaultDependencyResolver.Resolve(CreationContext context, ISubDependencyResolver contextHandlerResolver, ComponentModel model, DependencyModel dependency)
   at Castle.MicroKernel.ComponentActivator.DefaultComponentActivator.CreateConstructorArguments(ConstructorCandidate constructor, CreationContext context)
   at Castle.MicroKernel.ComponentActivator.DefaultComponentActivator.Instantiate(CreationContext context)
   at Castle.MicroKernel.ComponentActivator.DefaultComponentActivator.InternalCreate(CreationContext context)
   at Castle.MicroKernel.ComponentActivator.AbstractComponentActivator.Create(CreationContext context, Burden burden)
   at Castle.MicroKernel.Lifestyle.AbstractLifestyleManager.CreateInstance(CreationContext context, Boolean trackedExternally)
   at Castle.MicroKernel.Lifestyle.AbstractLifestyleManager.Resolve(CreationContext context, IReleasePolicy releasePolicy)
   at Castle.MicroKernel.Handlers.DefaultHandler.ResolveCore(CreationContext context, Boolean requiresDecommission, Boolean instanceRequired, Burden& burden)
   at Castle.MicroKernel.Handlers.DefaultHandler.Resolve(CreationContext context, Boolean instanceRequired)
   at Castle.MicroKernel.DefaultKernel.ResolveComponent(IHandler handler, Type service, Arguments additionalArguments, IReleasePolicy policy, Boolean ignoreParentContext)
   at Castle.MicroKernel.DefaultKernel.Castle.MicroKernel.IKernelInternal.Resolve(Type service, Arguments arguments, IReleasePolicy policy, Boolean ignoreParentContext)
   at Castle.MicroKernel.DefaultKernel.Resolve(Type service, Arguments arguments)
   at Castle.Windsor.WindsorContainer.Resolve[T]()
   at OSPSuite.Infrastructure.Container.Castle.CastleWindsorContainer.Resolve[TInterface]()
   at OSPSuite.Presentation.Core.ApplicationController.Start[TPresenter]()
   at PKSim.Presentation.Services.EditParameterPresenterTask.EditTableFor(ICommandCollector presenter, IParameterDTO parameterDTO) in C:\SW-Dev\PK-Sim\branches\11.0\src\PKSim.Presentation\Services\EditParameterPresenterTask.cs:line 46
   at PKSim.Presentation.Presenters.Parameters.EditParameterPresenter`2.EditTableFor(IParameterDTO parameterDTO) in C:\SW-Dev\PK-Sim\branches\11.0\src\PKSim.Presentation\Presenters\Parameters\EditParameterPresenter.cs:line 63
   at PKSim.UI.Views.Parameters.ParameterSetView.editTable() in C:\SW-Dev\PK-Sim\branches\11.0\src\PKSim.UI\Views\Parameters\ParameterSetView.cs:line 144
   at OSPSuite.UI.Controls.BaseUserControl.<>c__DisplayClass23_0.<OnEvent>b__0()
   at OSPSuite.Utility.Extensions.ExceptionExtensions.DoWithinExceptionHandler(Object callerObject, Action actionToExecute)
```

### PR DESCRIPTION
**Pull request by rwmcintosh**
Fixes #2981 

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Type of change

Please mark relevant options with an `x` in the brackets.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires documentation changes (link at least one [user](https://github.com/Open-Systems-Pharmacology/docs) or [developer](https://github.com/Open-Systems-Pharmacology/developer-docs) documentation issue):
- [ ] Algorithm update - updates algorithm documentation/questions/answers etc.
- [ ] Other (please describe):

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Integration tests
- [ ] Unit tests
- [x] Manual tests 
- [ ] No tests required

# Reviewer checklist

Mark everything that needs to be checked before merging the PR.

- [ ] Check if the code is well documented
- [ ] Check if the behavior is what is expected
- [ ] Check if the code is well tested
- [ ] Check if the code is readable and well formatted
- [ ] Additional checks (document below if any)
- [ ] Check if documentation update issue(s) are created if the option `This change requires a documentation update` above is selected

# Screenshots (if appropriate):

# Questions (if appropriate):

### CODE REVIEW

File: src/PKSim.Presentation/Presenters/Parameters/TableParameterPresenter.cs [hunk 1]
```diff
@@ -143,4 +148,28 @@ private ValuePoint valuePointFrom(ValuePointDTO valuePointDTO)
...
+      }
+
+      protected override TableFormula TablePointsToTableFormula(DataRepository importedTablePoints)
+      {
+         // default import function disabled when context is not specified
+         throw new System.NotImplementedException();
+      }
+
+      public override bool CanImport => false;
+   }
```
Comment (rwmcintosh) [inline src/PKSim.Presentation/Presenters/Parameters/TableParameterPresenter.cs:174]: The class went missing as I moved presenters around to get table formula view in MoBi. 

This particular presenter did not allow import from Excel

File: src/PKSim.Presentation/Presenters/Parameters/TableParameterPresenter.cs [hunk 2]
```diff
@@ -143,4 +148,28 @@ private ValuePoint valuePointFrom(ValuePointDTO valuePointDTO)
...
+         base(view, parameterTask, formulaFactory, cloner)
+      {
+         // default import function disabled when context is not specified
+         view.ImportVisible = CanImport;
+      }
+
+      protected override DataRepository ImportTablePoints()
+      {
+         // default import function disabled when context is not specified
+         throw new System.NotImplementedException();
```
Comment (Yuri05) [inline src/PKSim.Presentation/Presenters/Parameters/TableParameterPresenter.cs:164]: NotImplementedException?

Comment (rwmcintosh) [reply src/PKSim.Presentation/Presenters/Parameters/TableParameterPresenter.cs:164]: Yeah, the interface requires these methods, but to satisfy the button for import, however, in this case the button is hidden with the comment that import is not allowed. We could return DataRepos and TableFormula or return null to avoid this ugly sight

**Review by Yuri05 — APPROVED** [review]
